services:
  # Update this image with whatever image you have access to
  brapi-java-server-v1:
    image: brapicoordinatorselby/brapi-java-server:v1
    depends_on:
      - postgres
    volumes:
      - /home/jenkins/brapi.org/brapi-test-server/properties/v1/application.properties:/home/brapi/properties/application.properties
  brapi-java-server-v2:
    # Update this image with whatever image you have access to
    image: brapicoordinatorselby/brapi-java-server:v2
    depends_on:
      - postgres
    volumes:
      # Update this path with the path your pipeline tool expects
      - /home/jenkins/brapi.org/brapi-test-server/properties/v2/application.properties:/home/brapi/properties/application.properties
  keycloak-brapi:
    # Update this image with whatever keycloak image you have access to
    image: brapicoordinatorselby/brapi-keycloak:latest
    entrypoint: /opt/keycloak/bin/kc.sh start --optimized --proxy edge
    depends_on:
      - postgres
    environment:
      # These vars will change depending on how you have configured your keycloak DB
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - KC_HOSTNAME=auth.brapi.org
      - KC_DB
      - KC_DB_URL
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
  postgres:
    image: postgres:13
    volumes:
      # Update this path with the path your pipeline tool expects
      - /home/jenkins/brapi.org/brapi-test-server/data:/var/lib/postgresql/data
networks:
    default:
        external:
            name: brapi_net
