version: '3'

services:
  brapi-java-server-v1:
    image: brapicoordinatorselby/brapi-java-server:v1
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /home/jenkins/brapi.org/brapi-test-server/properties/v1/application.properties:/home/brapi/properties/application.properties
  brapi-java-server-v2:
    image: brapicoordinatorselby/brapi-java-server:v2
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /home/jenkins/brapi.org/brapi-test-server/properties/v2/application.properties:/home/brapi/properties/application.properties
  keycloak-brapi:
    image: brapicoordinatorselby/brapi-keycloak:latest
    restart: unless-stopped
    entrypoint: /opt/keycloak/bin/kc.sh start --optimized --proxy edge
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - KC_HOSTNAME=auth.brapi.org
      - KC_DB
      - KC_DB_URL
      - KC_DB_USERNAME
      - KC_DB_PASSWORD
  postgres:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /home/jenkins/brapi.org/brapi-test-server/data:/var/lib/postgresql/data
networks:
    default:
        external:
            name: brapi_net
