/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api.core;

import io.swagger.model.BrAPIResponse;
import io.swagger.model.Model202AcceptedSearchResponse;
import io.swagger.model.core.*;
import io.swagger.annotations.*;

import org.brapi.test.BrAPITestServer.exceptions.BrAPIServerException;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import jakarta.validation.Valid;

import java.util.ArrayList;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-03-20T16:31:52.030Z[GMT]")
@Api(value = "batches", description = "the batches API")
public interface BatchesApi {

    @ApiOperation(value = "Get the details of a specific Batch", nickname = "batchesBatchDbIdGet", notes = "Get a specific generic batches", response = BatchesSingleResponse.class, authorizations = {
            @Authorization(value = "AuthorizationToken") }, tags = { "Batches", })
    @ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = BatchesSingleResponse.class),
            @ApiResponse(code = 400, message = "Bad Request", response = String.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
            @ApiResponse(code = 403, message = "Forbidden", response = String.class),
            @ApiResponse(code = 404, message = "Not Found", response = String.class) })
    @RequestMapping(value = "/batches/{batchDbId}", produces = { "application/json" }, method = RequestMethod.GET)
    ResponseEntity<BatchesSingleResponse> batchesBatchDbIdGet(
            @ApiParam(value = "The unique ID of this generic batch", required = true) @PathVariable("batchDbId") String batchDbId,
            @ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>") @RequestHeader(value = "Authorization", required = false) String authorization)
            throws BrAPIServerException;

    @ApiOperation(value = "Add Items to a specific Batch", nickname = "batchesBatchDbIdItemsPost", notes = "Add new data to a specific generic batches", response = BatchResponse.class, authorizations = {
            @Authorization(value = "AuthorizationToken") }, tags = { "Batches", })
    @ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = BatchResponse.class),
            @ApiResponse(code = 400, message = "Bad Request", response = String.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
            @ApiResponse(code = 403, message = "Forbidden", response = String.class),
            @ApiResponse(code = 404, message = "Not Found", response = String.class) })
    @RequestMapping(value = "/batches/{batchDbId}/items", produces = { "application/json" }, consumes = {
            "application/json" }, method = RequestMethod.POST)
    ResponseEntity<BatchResponse> batchesBatchDbIdItemsPost(
            @ApiParam(value = "The unique ID of this generic batch", required = true) @PathVariable("batchDbId") String batchDbId,
            @ApiParam(value = "") @Valid @RequestBody ArrayList<String> body,
            @ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>") @RequestHeader(value = "Authorization", required = false) String authorization)
            throws BrAPIServerException;

    @ApiOperation(value = "Add Items to a specific Batch", nickname = "batchesBatchDbIdDataPost", notes = "Add new data to a specific generic batches", response = BatchResponse.class, authorizations = {
            @Authorization(value = "AuthorizationToken") }, tags = { "Batches", })
    @ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = BatchResponse.class),
            @ApiResponse(code = 400, message = "Bad Request", response = String.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
            @ApiResponse(code = 403, message = "Forbidden", response = String.class),
            @ApiResponse(code = 404, message = "Not Found", response = String.class) })
    @RequestMapping(value = "/batches/{batchDbId}/data", produces = { "application/json" }, consumes = {
            "application/json" }, method = RequestMethod.POST)
    ResponseEntity<BatchResponse> batchesBatchDbIdDataPost(
            @ApiParam(value = "The unique ID of this generic batch", required = true) @PathVariable("batchDbId") String batchDbId,
            @ApiParam(value = "") @Valid @RequestBody ArrayList<String> body,
            @ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>") @RequestHeader(value = "Authorization", required = false) String authorization)
            throws BrAPIServerException;

    @ApiOperation(value = "Update an existing generic batch", nickname = "batchesBatchDbIdPut", notes = "Update an existing generic batch", response = BatchesSingleResponse.class, authorizations = {
            @Authorization(value = "AuthorizationToken") }, tags = { "Batches", })
    @ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = BatchesSingleResponse.class),
            @ApiResponse(code = 400, message = "Bad Request", response = String.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
            @ApiResponse(code = 403, message = "Forbidden", response = String.class),
            @ApiResponse(code = 404, message = "Not Found", response = String.class) })
    @RequestMapping(value = "/batches/{batchDbId}", produces = { "application/json" }, consumes = {
            "application/json" }, method = RequestMethod.PUT)
    ResponseEntity<BatchesSingleResponse> batchesBatchDbIdPut(
            @ApiParam(value = "The unique ID of this generic batch", required = true) @PathVariable("batchDbId") String batchDbId,
            @ApiParam(value = "") @Valid @RequestBody BatchNewRequest body,
            @ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>") @RequestHeader(value = "Authorization", required = false) String authorization)
            throws BrAPIServerException;

    @ApiOperation(value = "Create a New Batch", nickname = "batchesPost", notes = "Create a new batch", response = BatchesListResponse.class, authorizations = {
            @Authorization(value = "AuthorizationToken") }, tags = { "Batches", })
    @ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = BatchesListResponse.class),
            @ApiResponse(code = 400, message = "Bad Request", response = String.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
            @ApiResponse(code = 403, message = "Forbidden", response = String.class) })
    @RequestMapping(value = "/batches", produces = { "application/json" }, consumes = {
            "application/json" }, method = RequestMethod.POST)
    ResponseEntity<? extends BrAPIResponse> batchesPost(@ApiParam(value = "") @Valid @RequestBody BatchSearchRequest body,
            @ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>") @RequestHeader(value = "Authorization", required = false) String authorization)
            throws BrAPIServerException;

    @ApiOperation(value = "Get the results of a Batch search request", nickname = "searchBatchesSearchResultsDbIdGet", notes = "Advanced searching for the batch resource. See Search Services for additional implementation details.", response = BatchesListResponse.class, authorizations = {
            @Authorization(value = "AuthorizationToken") }, tags = { "Batches", })
    @ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = BatchesListResponse.class),
            @ApiResponse(code = 202, message = "Accepted", response = Model202AcceptedSearchResponse.class),
            @ApiResponse(code = 400, message = "Bad Request", response = String.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
            @ApiResponse(code = 403, message = "Forbidden", response = String.class) })
    @RequestMapping(value = "/search/batches/{searchResultsDbId}", produces = {
            "application/json" }, method = RequestMethod.GET)
    ResponseEntity<? extends BrAPIResponse> searchBatchesSearchResultsDbIdGet(
            @ApiParam(value = "Permanent unique identifier which references the search results", required = true) @PathVariable("searchResultsDbId") String searchResultsDbId,
            @ApiParam(value = "page") @Valid @RequestParam(value = "page", required = false) Integer page,
            @ApiParam(value = "pageSize") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,
            @ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>") @RequestHeader(value = "Authorization", required = false) String authorization) throws BrAPIServerException;

    @ApiOperation(value = "Delete a specific Batch", nickname = "batchesBatchDbIdDelete", notes = "Delete a specific generic batch", response = BatchesSingleResponse.class, authorizations = {
            @Authorization(value = "AuthorizationToken") }, tags = { "Batches", })
    @ApiResponses(value = { @ApiResponse(code = 200, message = "OK", response = BatchesSingleResponse.class),
            @ApiResponse(code = 400, message = "Bad Request", response = String.class),
            @ApiResponse(code = 401, message = "Unauthorized", response = String.class),
            @ApiResponse(code = 403, message = "Forbidden", response = String.class),
            @ApiResponse(code = 404, message = "Not Found", response = String.class) })
    @RequestMapping(value = "/batches/{batchDbId}", produces = { "application/json" }, method = RequestMethod.DELETE)
    ResponseEntity<BatchesSingleResponse> batchesBatchDbIdDelete(
            @ApiParam(value = "The unique ID of this generic batch", required = true) @PathVariable("batchDbId") String batchDbId,
            @ApiParam(value = "HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong>") @RequestHeader(value = "Authorization", required = false) String authorization)
            throws BrAPIServerException;

}